# Generated by Django 3.1.5 on 2021-01-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
