# Generated by Django 3.1.5 on 2021-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_upload',
            field=models.FileField(default='default.pdf', upload_to='Book_file'),
        ),
    ]
