# Generated by Django 3.1.5 on 2021-03-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_book_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
